version: "3.3"
services:
  cs:
    build: .
    network_mode: host
    volumes:
      - .://usr/src/app
  postgres:
    image: postgres:14.4
    environment:
      - POSTGRES_PASSWORD=123qwe
      - POSTGRES_USER=destek
      - POSTGRES_DB=destek
    ports:
      - '5432:5432'
    volumes:
      - ./src/sql/ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
      - postgres:/var/lib/postgresql/data
  redis:
    image: redis:6.2.7
    ports:
      - '6379:6379'
  elastic:
    image: elasticsearch:7.17.5
    environment:
      - discovery.type=single-node
    ports:
      - '9200:9200'
      - '9300:9300'
    volumes:
      - elastic:/usr/share/elasticsearch/data
volumes:
  postgres: {}
  elastic: {}