version: "3.3"
services:
  cs:
    build: .
    # environment:
    #   - NODE_ENV=production
    #   - DEBUG=""
    ports:
      - '4000:4000'
    volumes:
      - .://usr/src/app
    networks:
      - cs-net
  postgres:
    image: postgres:14.4
    environment:
      - POSTGRES_PASSWORD=123qwe
      - POSTGRES_USER=destek
      - POSTGRES_DB=destek
    volumes:
      - ./src/sql/ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
      - postgres:/var/lib/postgresql/data
    networks:
      - cs-net
  redis:
    image: redis:6.2.7
    networks:
      - cs-net
  elastic:
    image: elasticsearch:7.17.5
    environment:
      - discovery.type=single-node
    volumes:
      - elastic:/usr/share/elasticsearch/data
    networks:
      - cs-net
volumes:
  postgres: {}
  elastic: {}
networks:
  cs-net: 